import { skipWaiting, clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

// Ensure the service worker takes over the client as soon as it's activated
skipWaiting();
clientsClaim();

// Precache assets - usually generated by Workbox during the build step
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache CSS and JS files
registerRoute(
    /\.(?:js|css)$/,
    new StaleWhileRevalidate({
        cacheName: 'js-css-cache',
    })
);

// Cache image files
registerRoute(
    /\.(?:png|jpg|jpeg|svg|gif)$/,
    new CacheFirst({
        cacheName: 'image-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50, // Only store the 50 most recently accessed images
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// You can add more caching strategies based on your needs, e.g., for fonts or API calls.
